apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customerservice
  name: customerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customerservice
    spec:
      containers:
      - image: customerservice
        imagePullPolicy: "Never"
        name: customerservice
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customerservice
  name: customerservice
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    app: customerservice
  type: ClusterIP
status:
  loadBalancer: {}
