apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orderservice
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orderservice
    spec:
      containers:
      - image: orderservice
        imagePullPolicy: "Never"
        name: orderservice
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orderservice
  name: orderservice
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    app: orderservice
  type: ClusterIP
status:
  loadBalancer: {}
